version: "3"
 
volumes: # 自定义数据卷，位于宿主机/var/lib/docker/volumes内
  myproject_media_vol: # 定义数据卷同步media文件夹数据
 
services:
  web:
    build: ./backend # 使用backend目录下的Dockerfile
    expose:
       - "8000"
    volumes:
       - ./backend:/var/www/html/backend # 挂载项目代码
       - myproject_media_vol:/var/www/html/backend/media # 以数据卷挂载容器内用户上传媒体文件
    restart: always
    tty: true
    stdin_open: true
 
  nginx:
    build: ./compose/nginx
    ports:
       - "80:80"
    expose:
       - "80"
    volumes:
       - ./backend/static:/usr/share/nginx/html/static # 挂载静态文件
       - ./compose/nginx/log:/var/log/nginx # 挂载日志
       - myproject_media_vol:/usr/share/nginx/html/media # 挂载用户上传媒体文件
    links:
       - web
    depends_on:
       - web
    restart: always