# Generated by Django 3.2.10 on 2022-11-17 21:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('content', models.TextField(help_text='内容', verbose_name='内容')),
            ],
            options={
                'verbose_name': '用户资源',
                'verbose_name_plural': '用户资源',
            },
        ),
        migrations.CreateModel(
            name='ResourceLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间')),
                ('modified_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否已删除')),
                ('is_limited', models.BooleanField(default=False, help_text='是否配额', verbose_name='是否配额')),
                ('max_limit', models.IntegerField(help_text='配额最大数', verbose_name='配额最大数')),
            ],
            options={
                'verbose_name': '用户资源配额',
                'verbose_name_plural': '用户资源配额',
            },
        ),
    ]
