# Generated by Django 3.2.10 on 2022-11-17 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcelimit',
            name='creator',
            field=models.ForeignKey(help_text='创建人', on_delete=django.db.models.deletion.PROTECT, related_name='resourcelimit_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='resourcelimit',
            name='modifier',
            field=models.ForeignKey(help_text='修改人', on_delete=django.db.models.deletion.PROTECT, related_name='resourcelimit_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
        migrations.AddField(
            model_name='resourcelimit',
            name='user',
            field=models.ForeignKey(help_text='配额用户', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='配额用户'),
        ),
        migrations.AddField(
            model_name='resource',
            name='creator',
            field=models.ForeignKey(help_text='创建人', on_delete=django.db.models.deletion.PROTECT, related_name='resource_creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='resource',
            name='modifier',
            field=models.ForeignKey(help_text='修改人', on_delete=django.db.models.deletion.PROTECT, related_name='resource_modifier', to=settings.AUTH_USER_MODEL, verbose_name='修改人'),
        ),
    ]
